/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StudentController;
import Model.StudentTable;
import Model.StudentSection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;  

/**
 *
 * @author janis
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    private StudentController controller;
    
    
    public Student() {
        initComponents();
       
        controller = new StudentController();
        populateStudentTable();
    }
    
    private void populateStudentTable() {
        List<StudentTable> students = controller.getAllStudents();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Clear existing rows
        model.setRowCount(0);

        // Add rows from the student list
        for (StudentTable student : students) {
            model.addRow(new Object[]{
                    student.getIndexNumber(),
                    student.getFirstName(),
                    student.getLastName(),
                    student.getDegree(),
                    student.getEmail(),
                    student.getPhone()
            });
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox = new javax.swing.JLabel();
        txtlast = new javax.swing.JLabel();
        txtindex = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        txtphone = new javax.swing.JLabel();
        txtfirst3 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        studentemail = new javax.swing.JTextField();
        phonetxt = new javax.swing.JTextField();
        indexnumber = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        searchbar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combobox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobox.setForeground(new java.awt.Color(102, 102, 102));
        combobox.setText("Degree Program :");
        getContentPane().add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 153, 26));

        txtlast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtlast.setForeground(new java.awt.Color(102, 102, 102));
        txtlast.setText("Last Name           :");
        getContentPane().add(txtlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 153, 26));

        txtindex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtindex.setForeground(new java.awt.Color(102, 102, 102));
        txtindex.setText("Index Number    :");
        getContentPane().add(txtindex, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 153, 26));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(102, 102, 102));
        txtemail.setText("Student email     :");
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 153, 26));

        txtphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(102, 102, 102));
        txtphone.setText("Contact Number:");
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 143, 26));

        txtfirst3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfirst3.setForeground(new java.awt.Color(102, 102, 102));
        txtfirst3.setText("First Name           :");
        getContentPane().add(txtfirst3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 153, 26));

        firstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(159, 195, 208)));
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 360, 40));

        lastname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(159, 195, 208)));
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 360, 40));

        studentemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studentemail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(159, 195, 208)));
        getContentPane().add(studentemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 360, 40));

        phonetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phonetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(159, 195, 208)));
        phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetxtActionPerformed(evt);
            }
        });
        getContentPane().add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 360, 40));

        indexnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        indexnumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(159, 195, 208)));
        getContentPane().add(indexnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 360, 40));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Degree Program", "BSc(Hons) in Information Technology", "BIT(Hons) in Net. and Mobi. Computing", "BIT (Moratuwa)" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(159, 195, 208)));
        jComboBox1.setMinimumSize(new java.awt.Dimension(69, 22));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 360, 50));

        jButton1.setBackground(new java.awt.Color(141, 198, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("ADD NEW");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 90, 40));

        jButton2.setBackground(new java.awt.Color(141, 194, 208));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 90, 40));

        jButton3.setBackground(new java.awt.Color(141, 198, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 90, 40));

        jButton4.setBackground(new java.awt.Color(159, 195, 208));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, 100, 40));

        searchbar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 195, 208), 2));
        getContentPane().add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 350, 40));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Index Number", "First Name ", "Last Name", "Degree Program", "Student Email", "Contact Number"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(32);
        jTable1.setRowMargin(8);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 680, 350));

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("GO BACK");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 90, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Index Number   :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/attendance management syatem (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 730));

        setSize(new java.awt.Dimension(1305, 771));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String indexNumbertxt = indexnumber.getText();
        String firstName = firstname.getText();
        String lastName = lastname.getText();
        String degree = jComboBox1.getSelectedItem().toString();
        String email = studentemail.getText();
        String phone = phonetxt.getText();

        if (indexNumbertxt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Index number is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int indexNumber;
        try {
            indexNumber = Integer.parseInt(indexNumbertxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Index number must be an integer", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = controller.updateStudent(indexNumber, firstName, lastName, degree, email, phone);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Student updated successfully!");
            populateStudentTable(); // Refresh the table after updating a student
            clearField(); // Clear fields after successful update
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update student!", "Error", JOptionPane.ERROR_MESSAGE);
        }
         
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void phonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String indexNumber = indexnumber.getText();
    String firstName = firstname.getText();
    String lastName = lastname.getText();
    String degree = jComboBox1.getSelectedItem().toString();
    String email = studentemail.getText();
    String phone = phonetxt.getText();

    if (controller.checkIfIndexNumberExists(indexNumber)) {
        JOptionPane.showMessageDialog(this, "Index number already exists!", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        boolean success = controller.addStudent(indexNumber, firstName, lastName, degree, email, phone);
        if (success) {
            JOptionPane.showMessageDialog(this, "Student added successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add student!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } populateStudentTable();
}

// Method to clear the fields after submitting
private void clearField() {
    indexnumber.setText("");
    firstname.setText("");
    lastname.setText("");
    jComboBox1.setSelectedIndex(0);
    studentemail.setText("");
    phonetxt.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Dashboard obj = new Dashboard();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow >= 0) {
        indexnumber.setText(jTable1.getValueAt(selectedRow, 0).toString());
        firstname.setText(jTable1.getValueAt(selectedRow, 1).toString());
        lastname.setText(jTable1.getValueAt(selectedRow, 2).toString());
        jComboBox1.setSelectedItem(jTable1.getValueAt(selectedRow, 3).toString());
        studentemail.setText(jTable1.getValueAt(selectedRow, 4).toString());
        phonetxt.setText(jTable1.getValueAt(selectedRow, 5).toString());

        // Clear existing rows in the table model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // Add rows from the student list
        List<StudentTable> students = controller.getAllStudents();  // Replace with your actual method to fetch students
        for (StudentTable student : students) {
            model.addRow(new Object[]{
                student.getIndexNumber(),
                student.getFirstName(),
                student.getLastName(),
                student.getDegree(),
                student.getEmail(),
                student.getPhone()
            });
        }
    }
            
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String indexNumber = indexnumber.getText();
    
    
    int index = Integer.parseInt(indexNumber);
    
    // Confirm before deleting
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this student?", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        boolean success = controller.deleteStudent(index);
        if (success) {
            JOptionPane.showMessageDialog(this, "Student deleted successfully!");
            populateStudentTable(); // Refresh the table after deletion
            clearField(); // Clear fields after successful deletion
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete student!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String indexNumber = searchbar.getText().trim();
            
            if (!indexNumber.isEmpty()) {
                // Call search method in StudentController
                StudentTable student = controller.searchStudentByIndex(indexNumber);
                
                if (student != null) {
                    // Populate text fields with found student data
                    indexnumber.setText(student.getIndexNumber());
                    firstname.setText(student.getFirstName());
                    lastname.setText(student.getLastName());
                    jComboBox1.setSelectedItem(student.getDegree());
                    studentemail.setText(student.getEmail());
                    phonetxt.setText(student.getPhone());
                    
                    // Optionally, notify user or update UI after successful search
                    JOptionPane.showMessageDialog(null, "Student found!");
                } else {
                    // Clear text fields or show message indicating student not found
                    clearField();
                    JOptionPane.showMessageDialog(null, "Student not found!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please enter an index number to search.");
            }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel combobox;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField indexnumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JTextField searchbar;
    private javax.swing.JTextField studentemail;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtfirst3;
    private javax.swing.JLabel txtindex;
    private javax.swing.JLabel txtlast;
    private javax.swing.JLabel txtphone;
    // End of variables declaration//GEN-END:variables
}
